### ISSUE TITLE
Problem with creating hexagons

### ISSUE THREAD

**Issue by LAGIS-BR** [ZGIS/ZonalMetrics-Toolbox_ArcGIS_Pro#2]
Sorry, but there is still a problem....
The newest version is the one you updated 14 days ago?

Running script CreateHexagons...
ZonalMetricsTool version: 2020324_11
Debug mode disabled
create hexagon layer....
height: 50.0
width: 86.60254037844386
 Traceback (most recent call last):
  File "<string>", line 1651, in execute
  File "<string>", line 1778, in updateOrigin
ValueError: could not convert string to float: '5689478,1331'
 Failed to execute (CreateHexagons).

_Originally posted by @LAGIS-BR in https://github.com/ZGIS/ZonalMetrics-Toolbox_ArcGIS_Pro/issues/1#issuecomment-611494601_

**Comment by dtiede** [comment]
There was a problem with comma as decimal separator in the extent definition. Should now work with the new version (upload 09042020 15:15). Please check
