### ISSUE TITLE
Create hexagons: error messages from UNIGIS students

### ISSUE THREAD

**Issue by LAGIS-BR** [ZGIS/ZonalMetrics-Toolbox_ArcGIS_Pro#3]
![image](https://user-images.githubusercontent.com/62549615/82180528-0197a380-98e1-11ea-9c9e-27bba6d24794.png)

looks like an "old issue, but the link provided is: https://github.com/ZGIS/ZonalMetrics-Toolbox_ArcGIS_Pro
BUT the readme document provides only the link to the old version - can please change that to avoid confusion?

**Comment by dtiede** [comment]
most likely the input data set is not supported (Shapefiles and ESRI File Geodatabases are supporter). Readme is pointing to the Python 2.x version for ArcGIS Dekstop >> as expected.
