### ISSUE TITLE
ED with statistical layer: AOI

### ISSUE THREAD

**Issue by LAGIS-BR** [ZGIS/ZonalMetrics-Toolbox_ArcGIS_Pro#4]
![snip_20200602082354](https://user-images.githubusercontent.com/62549615/83487281-0cd6fb80-a4ab-11ea-90a8-d0d719225305.png)

Kann es sein, dass es nicht funktioniert weil keine Klasen ausgewählt wurden? (funktioniert komischerweise mit gleichen Einstellungen bei Hexagonen lt. Studentin)?

**Comment by dtiede** [comment]
das war ein Bug in der Toolbox in Zusammenhang mit der Geodatabase. Danach wurdewahrscheinlich das Shapefile aus der Feature Class erstellt, bei der schon (leere) Felder zu Zonal Area und UnitID angelegt waren. Deswegen hat es dann auch mit dem Shapefile nicht geklappt.

Ich habe die Toolbox gerade upgedated. Trotzdem darauf achten, dass die Felder für die Edge Metrics vor der Anwendung nicht mit leeren Werten in der Feature Class vorkommen.

**Comment by LAGIS-BR** [comment]
Hi Dirk,

danke! Um ehrlich zu sein verstehe ich nicht wirklich was du meinst/das Problem war…..könntest du mir das mal erklären?

Danke und lg,
Babsi

Von: dtiede <notifications@github.com>
Gesendet: Samstag, 6. Juni 2020 21:01
An: ZGIS/ZonalMetrics-Toolbox_ArcGIS_Pro <ZonalMetrics-Toolbox_ArcGIS_Pro@noreply.github.com>
Cc: Riedler Barbara <Barbara.Riedler@sbg.ac.at>; Author <author@noreply.github.com>
Betreff: Re: [ZGIS/ZonalMetrics-Toolbox_ArcGIS_Pro] ED with statistical layer: AOI (#4)


das war ein Bug in der Toolbox in Zusammenhang mit der Geodatabase. Danach wurdewahrscheinlich das Shapefile aus der Feature Class erstellt, bei der schon (leere) Felder zu Zonal Area und UnitID angelegt waren. Deswegen hat es dann auch mit dem Shapefile nicht geklappt.

Ich habe die Toolbox gerade upgedated. Trotzdem darauf achten, dass die Felder für die Edge Metrics vor der Anwendung nicht mit leeren Werten in der Feature Class vorkommen.
